name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up ssh key and connect to the instance
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
        run: echo "$EC2_SSH_KEY" > "id_rsa.pem"
      - name: Connect to EC2 instance via ssh and pull changes
        run: chmod 400 id_rsa.pem && ssh -o StrictHostKeyChecking=no -i id_rsa.pem ubuntu@3.74.199.139 "
        cd /home/ubuntu/simple_server &&
        git checkout master -f &&
        sudo git pull"
      - name: Run app
        run: npm start
#      - name: Build docker image
#        run: docker build -t simple-server .
#      - name: Tag docker image
#        run: docker tag simple-server:latest simple-server:${{ github.run_number }}
#      - name: Remove old docker node
#        run: docker stop simple-server || true && docker rm simple-server || true
#      - name: Startup
#        run: npm run docker-run && curl 2ip.ru
