name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up ssh key and connect to the instance
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
        run: echo "$EC2_SSH_KEY" > "id_rsa.pem" && chmod 400 id_rsa.pem
      - name: Connect to EC2 instance via ssh and pull changes
        run: ssh -o StrictHostKeyChecking=no -i id_rsa.pem ubuntu@3.74.199.139 "cd /home/ubuntu/simple_server && sudo git checkout master -f && sudo git pull && sudo docker kill simple-server || true && sudo docker rm simple-server || true && sudo docker build -t simple-server . && npm run docker-run"
